import { Open_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ptBR } from '@clerk/localizations'
import type { Metadata } from 'next'
import { Toaster } from 'sonner'

import { ThemeProvider } from '@/components/providers/theme-provider'
import { NextUIProviders } from '@/components/providers/next-ui'
import { SearchCommand } from '@/components/search-commander'

import './styles/globals.css'
import { cn } from '@/lib/utils'
import { STORAGE_KEYS } from '@/constants/general'

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Grizzle',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="antialiased" suppressHydrationWarning>
      <body className={cn(openSans.className, 'bg-zinc-50 dark:bg-zinc-800')}>
        <ClerkProvider localization={ptBR}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey={STORAGE_KEYS.GRIZZLE_THEME}
          >
            <NextUIProviders>
              <Toaster position="bottom-center" />
              <SearchCommand />
              {children}
            </NextUIProviders>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}
